spring:
  liquibase:
    change-log: db/changelog/master.xml
  datasource:
    url: "jdbc:postgresql://paganell.webtm.ru:5432/category_tree"
    username: "paganell"
    password: "12345"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql

bot:
  username: Category Tree Bot
  token: 6907782664:AAFME4ezipCgFIm6_0FMMfZnKIVcenNGie8


