spring:
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
  datasource:
    url: "jdbc:postgresql://localhost:5432/category_tree"
    username: "user"
    password: "12345"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect

bot:
  username: Category Tree Bot
  token: 6907782664:AAFME4ezipCgFIm6_0FMMfZnKIVcenNGie8


